service: aws-subastas
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: 
        - "arn:aws:dynamodb:us-east-1:103650216262:table/SubastasTable"

resources:
  Resources:
    SubastasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SubastasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  crearSubasta:
    handler: src/handlers/crearSubasta.handler
    events:
      - httpApi:
          path: /subasta
          method: POST
  listarSubastas:
    handler: src/handlers/listarSubastas.handler
    events:
      - httpApi:
          path: /subastas
          method: GET
  obtenerSubasta:
    handler: src/handlers/obtenerSubasta.handler
    events:
      - httpApi:
          path: /subasta/{id}
          method: GET

custom:
  bundle:
    linting: false
