service: aws-subastas
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource: 
        - "arn:aws:dynamodb:us-east-1:103650216262:table/SubastasTable"
        - !Join ['/', [ arn:aws:dynamodb:us-east-1:103650216262:table/SubastasTable, 'index', 'estadoFechaFinIndex' ]]

resources:
  Resources:
    SubastasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SubastasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: estado
            AttributeType: S
          - AttributeName: fechaFin
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: estadoFechaFinIndex
            KeySchema:
              - AttributeName: estado
                KeyType: HASH
              - AttributeName: fechaFin
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL      
        BillingMode: PAY_PER_REQUEST

functions:
  crearSubasta:
    handler: src/handlers/crearSubasta.handler
    events:
      - httpApi:
          path: /subasta
          method: POST
  listarSubastas:
    handler: src/handlers/listarSubastas.handler
    events:
      - httpApi:
          path: /subastas
          method: GET
  obtenerSubasta:
    handler: src/handlers/obtenerSubasta.handler
    events:
      - httpApi:
          path: /subasta/{id}
          method: GET
  hacerOferta:
    handler: src/handlers/hacerOferta.handler
    events:
      - httpApi:
          path: /subasta/{id}/ofertar
          method: PATCH
  procesarSubastas:
    handler: src/handlers/procesarSubastas.handler
    #events:
      #- schedule: rate(1 minute)

custom:
  bundle:
    linting: false
