service: aws-subastas
configValidationMode: error
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    MAIL_QUEUE_URL: ${self:custom.mailQueue.url}
  iam:
    role:
      statements:
        - ${file(./iam/subastasTableIAM.yml):SubastasTableIAM}
        - ${file(./iam/mailQueueIAM.yml):MailQueueIAM} 

resources:
  Resources:
    SubastasTable: ${file(./resources/subastasTable.yml):SubastasTable} 

functions:
  crearSubasta:
    handler: src/handlers/crearSubasta.handler
    events:
      - http:
          path: /subasta
          method: POST
          authorizer: ${self:custom.authorizer}
  listarSubastas:
    handler: src/handlers/listarSubastas.handler
    events:
      - http:
          path: /subastas
          method: GET
          authorizer: ${self:custom.authorizer}
  obtenerSubasta:
    handler: src/handlers/obtenerSubasta.handler
    events:
      - http:
          path: /subasta/{id}
          method: GET
          authorizer: ${self:custom.authorizer}
  hacerOferta:
    handler: src/handlers/hacerOferta.handler
    events:
      - http:
          path: /subasta/{id}/ofertar
          method: PATCH
          authorizer: ${self:custom.authorizer}
  procesarSubastas:
    handler: src/handlers/procesarSubastas.handler
    #events:
      #- schedule: rate(1 minute)

custom:
  authorizer: arn:aws:lambda:${aws:region}:${aws:accountId}:function:aws-auth-${sls:stage}-auth
  mailQueue:
    arn: ${cf:aws-notificaciones-${self:provider.stage}.MailQueueArn}
    url: ${cf:aws-notificaciones-${self:provider.stage}.MailQueueUrl}
  bundle:
    linting: false
