SubastasTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: SubastasTable
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: estado
        AttributeType: S
      - AttributeName: fechaFin
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: estadoFechaFinIndex
        KeySchema:
          - AttributeName: estado
            KeyType: HASH
          - AttributeName: fechaFin
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    BillingMode: PAY_PER_REQUEST
